In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

data=pd.read_csv("2. Cars Data1.csv")
print(data)

      Make                    Model   Type  Origin DriveTrain      MSRP  \
0    Acura                      MDX    SUV    Asia        All  $36,945
1    Acura           RSX Type S 2dr  Sedan    Asia      Front  $23,820
2    Acura                  TSX 4dr  Sedan    Asia      Front  $26,990
3    Acura                   TL 4dr  Sedan    Asia      Front  $33,195
4    Acura               3.5 RL 4dr  Sedan    Asia      Front  $43,755
..     ...                      ...    ...     ...        ...       ...
427  Volvo  C70 LPT convertible 2dr  Sedan  Europe      Front  $40,565
428  Volvo  C70 HPT convertible 2dr  Sedan  Europe      Front  $42,565
429  Volvo               S80 T6 4dr  Sedan  Europe      Front  $45,210
430  Volvo                      V40  Wagon  Europe      Front  $26,135
431  Volvo                     XC70  Wagon  Europe        All  $35,145

      Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  \
0    $33,337          3.5        6.0       265.0      17.0         23.0
1    $21,761          2.0        4.0       200.0      24.0         31.0
2    $24,647          2.4        4.0       200.0      22.0         29.0
3    $30,299          3.2        6.0       270.0      20.0         28.0
4    $39,014          3.5        6.0       225.0      18.0         24.0
..        ...         ...        ...         ...       ...          ...
427  $38,203          2.4        5.0       197.0      21.0         28.0
428  $40,083          2.3        5.0       242.0      20.0         26.0
429  $42,573          2.9        6.0       268.0      19.0         26.0
430  $24,641          1.9        4.0       170.0      22.0         29.0
431  $33,112          2.5        5.0       208.0      20.0         27.0

     Weight  Wheelbase  Length
0    4451.0      106.0   189.0
1    2778.0      101.0   172.0
2    3230.0      105.0   183.0
3    3575.0      108.0   186.0
4    3880.0      115.0   197.0
..      ...        ...     ...
427  3450.0      105.0   186.0
428  3450.0      105.0   186.0
429  3653.0      110.0   190.0
430  2822.0      101.0   180.0
431  3823.0      109.0   186.0

[432 rows x 15 columns]

In [4]:
data.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0

In [5]:
data.columns

Index(['Make', 'Model', 'Type', 'Origin', 'DriveTrain', 'MSRP', 'Invoice',
       'EngineSize', 'Cylinders', 'Horsepower', 'MPG_City', 'MPG_Highway',
       'Weight', 'Wheelbase', 'Length'],
      dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Make         428 non-null    object
 1   Model        428 non-null    object
 2   Type         428 non-null    object
 3   Origin       428 non-null    object
 4   DriveTrain   428 non-null    object
 5   MSRP         428 non-null    object
 6   Invoice      428 non-null    object
 7   EngineSize   428 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   428 non-null    float64
 10  MPG_City     428 non-null    float64
 11  MPG_Highway  428 non-null    float64
 12  Weight       428 non-null    float64
 13  Wheelbase    428 non-null    float64
 14  Length       428 non-null    float64
dtypes: float64(8), object(7)
memory usage: 50.8+ KB

In [7]:
data.describe()

,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
count,428.000000,426.000000,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000
mean,3.196729,5.807512,215.885514,20.060748,26.843458,3577.953271,108.154206,186.362150
std,1.108595,1.558443,71.836032,5.238218,5.741201,758.983215,8.311813,14.357991
min,1.300000,3.000000,73.000000,10.000000,12.000000,1850.000000,89.000000,143.000000
25%,2.375000,4.000000,165.000000,17.000000,24.000000,3104.000000,103.000000,178.000000
50%,3.000000,6.000000,210.000000,19.000000,26.000000,3474.500000,107.000000,187.000000
75%,3.900000,6.000000,255.000000,21.250000,29.000000,3977.750000,112.000000,194.000000
max,8.300000,12.000000,500.000000,60.000000,66.000000,7190.000000,144.000000,238.000000

In [8]:
data.isnull().sum()

Make           4
Model          4
Type           4
Origin         4
DriveTrain     4
MSRP           4
Invoice        4
EngineSize     4
Cylinders      6
Horsepower     4
MPG_City       4
MPG_Highway    4
Weight         4
Wheelbase      4
Length         4
dtype: int64

In [9]:
data.duplicated().sum()

np.int64(3)

In [12]:
data.Make.unique()

array(['Acura', 'Audi', 'BMW', nan, 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Ford', 'GMC', 'Honda', 'Hummer', 'Hyundai',
       'Infiniti', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Land Rover',
       'Lexus', 'Lincoln', 'MINI', 'Mazda', 'Mercedes-Benz', 'Mercury',
       'Mitsubishi', 'Nissan', 'Oldsmobile', 'Pontiac', 'Porsche', 'Saab',
       'Saturn', 'Scion', 'Subaru', 'Suzuki', 'Toyota', 'Volkswagen',
       'Volvo'], dtype=object)

In [13]:
data.Make.value_counts()

Make
Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Volkswagen       15
Chrysler         15
Dodge            13
Mitsubishi       13
Volvo            12
Jaguar           12
Hyundai          12
Subaru           11
Pontiac          11
Mazda            11
Lexus            11
Kia              11
Buick             9
Mercury           9
Lincoln           9
Saturn            8
Cadillac          8
Suzuki            8
Infiniti          8
GMC               8
Acura             7
Porsche           7
Saab              7
Land Rover        3
Oldsmobile        3
Jeep              3
Scion             2
Isuzu             2
MINI              2
Hummer            1
Name: count, dtype: int64

In [16]:
data[data["Weight"]>4000]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240","$40,075",3.0,6.0,220.0,18.0,25.0,4013.0,105.0,180.0
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.2,8.0,300.0,17.0,24.0,4024.0,109.0,193.0
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.2,8.0,330.0,17.0,24.0,4399.0,121.0,204.0
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.2,8.0,450.0,15.0,22.0,4024.0,109.0,191.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,Volkswagen,Touareg V6,SUV,Europe,All,"$35,515","$32,243",3.2,6.0,220.0,15.0,20.0,5086.0,112.0,187.0
415,Volkswagen,Phaeton 4dr,Sedan,Europe,Front,"$65,000","$59,912",4.2,8.0,335.0,16.0,22.0,5194.0,118.0,204.0
416,Volkswagen,Phaeton W12 4dr,Sedan,Europe,Front,"$75,000","$69,130",6.0,12.0,420.0,12.0,19.0,5399.0,118.0,204.0
419,Volkswagen,Passat W8,Wagon,Europe,Front,"$40,235","$36,956",4.0,8.0,270.0,18.0,25.0,4067.0,106.0,184.0
420,Volvo,XC90 T6,SUV,Europe,All,"$41,250","$38,851",2.9,6.0,268.0,15.0,20.0,4638.0,113.0,189.0

In [18]:
data.groupby("Origin")["MSRP"].sum().sort_values(ascending=False)

Origin
USA       $37,895 $26,545 $22,180 $26,470 $24,895 $28,34...
Asia      $36,945 $23,820 $26,990 $33,195 $43,755 $46,10...
Europe    $25,940 $35,940 $31,840 $33,430 $34,480 $36,64...
Name: MSRP, dtype: object

In [19]:
data.groupby("Origin")["MSRP"].sum().sort_values(ascending=True)

Origin
Europe    $25,940 $35,940 $31,840 $33,430 $34,480 $36,64...
Asia      $36,945 $23,820 $26,990 $33,195 $43,755 $46,10...
USA       $37,895 $26,545 $22,180 $26,470 $24,895 $28,34...
Name: MSRP, dtype: object

In [20]:
data.groupby("Origin")["MSRP"].max()

Origin
Asia      $89,765
Europe    $94,820
USA       $81,795
Name: MSRP, dtype: object

In [21]:
data.groupby("Origin")["MSRP"].min()

Origin
Asia       $10,280
Europe    $121,770
USA        $10,995
Name: MSRP, dtype: object